/*
 * mainFrame.java
 *
 * Created on December 17, 2016, 6:29 PM
 */
package qlsp;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import dao.sanphamDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import model.loaisp;
import model.sanpham;

/**
 *
 * @author toi
 */
public class mainFrame extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private DefaultComboBoxModel dcbm;
    private boolean isEdit = false;
    private int trang;
    ArrayList<loaisp> listLoaiSP = null;
    ArrayList<sanpham> listSanPham = null;

    /**
     * Creates new form mainFrame
     */
    public mainFrame() throws SQLException {
        initComponents();

        dtm = new DefaultTableModel();
        dtm.addColumn("Mã Sp");
        dtm.addColumn("Tên SP");
        dtm.addColumn("Giá");
        dtm.addColumn("Mã loại");

        dcbm = new DefaultComboBoxModel();
        listLoaiSP = new sanphamDAO().getListLoai();
        for (loaisp loai : listLoaiSP) {
            dcbm.addElement(loai.getTenloai());
        }
        cb_loaisp.setModel(dcbm);
        loaddata();
    }

    private void loaddata() throws SQLException {
        listSanPham = new sanphamDAO().getListSanPham();
        for (sanpham sp : listSanPham) {
            dtm.addRow(toObjectsData(sp));
        }
        jTable.setModel(dtm);
    }

    private void loaddataTrang(long sotrang) throws SQLException {
        listSanPham = new sanphamDAO().getTrang(sotrang);
        for (sanpham sp : listSanPham) {
            dtm.addRow(toObjectsData(sp));
        }
        jTable.setModel(dtm);
    }

    private static Object[] toObjectsData(sanpham sp) {
        Object[] objectsData = {sp.getMaSP(), sp.getTenSP(), sp.getDongia(), sp.getMaloai()};
        return objectsData;
    }

    private void xoaText() {
        txt_ma_sp.setText("");
        txt_ten_loai.setText("");
        txt_gia_ban.setText("");
    }

    private void showAll() throws SQLException {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        ArrayList<sanpham> listsp = new sanphamDAO().getListSanPham();
        for (sanpham sp : listsp) {
            Vector v = new Vector();
            v.add(sp.getMaSP());
            v.add(sp.getTenSP());
            v.add(sp.getDongia());
            v.add(sp.getMaloai());
            dtm.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ten_sp = new javax.swing.JLabel();
        txt_ma_sp = new javax.swing.JTextField();
        txt_ten_loai = new javax.swing.JTextField();
        jButton_them = new javax.swing.JButton();
        jButton_xoa = new javax.swing.JButton();
        jButton_sua = new javax.swing.JButton();
        jButton_luu = new javax.swing.JButton();
        jButton_kluu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_loaisp = new javax.swing.JComboBox();
        txt_gia_ban = new javax.swing.JTextField();
        jButton_pre = new javax.swing.JButton();
        jButton_next = new javax.swing.JButton();
        jLabel_trang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QLSP - Java");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Danh mục loại sản phẩm"); // NOI18N

        jLabel2.setText("Mã sp:"); // NOI18N

        txt_ten_sp.setText("Tên sp:"); // NOI18N

        jButton_them.setText("Thêm"); // NOI18N
        jButton_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themActionPerformed(evt);
            }
        });

        jButton_xoa.setText("Xóa"); // NOI18N
        jButton_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaActionPerformed(evt);
            }
        });

        jButton_sua.setText("Sửa"); // NOI18N
        jButton_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suaActionPerformed(evt);
            }
        });

        jButton_luu.setText("Lưu"); // NOI18N
        jButton_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_luuActionPerformed(evt);
            }
        });

        jButton_kluu.setText("K. Lưu"); // NOI18N

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Giá", "Loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel4.setText("Giá bán:"); // NOI18N

        jLabel5.setText("Loại sản phẩm:"); // NOI18N

        jButton_pre.setText("<");
        jButton_pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_preActionPerformed(evt);
            }
        });

        jButton_next.setText(">");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });

        jLabel_trang.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_sua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_luu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_kluu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_ten_sp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ma_sp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_ten_loai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_gia_ban))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_loaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_pre)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel_trang)
                            .addGap(12, 12, 12)
                            .addComponent(jButton_next))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ma_sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_gia_ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ten_sp)
                    .addComponent(txt_ten_loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cb_loaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_them)
                    .addComponent(jButton_xoa)
                    .addComponent(jButton_sua)
                    .addComponent(jButton_luu)
                    .addComponent(jButton_kluu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_pre)
                    .addComponent(jButton_next)
                    .addComponent(jLabel_trang))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        txt_ma_sp.setText(jTable.getValueAt(jTable.getSelectedRow(), 0).toString());
        txt_ten_loai.setText(jTable.getValueAt(jTable.getSelectedRow(), 1).toString());
        txt_gia_ban.setText(jTable.getValueAt(jTable.getSelectedRow(), 2).toString());
        try {
            String tenLoai = new sanphamDAO().tenLoai(jTable.getValueAt(jTable.getSelectedRow(), 3).toString());
            cb_loaisp.setSelectedItem(tenLoai);
        } catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println(ex);
        }
    }//GEN-LAST:event_jTableMouseClicked

    private void jButton_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themActionPerformed
        xoaText();
        isEdit = false;
    }//GEN-LAST:event_jButton_themActionPerformed

    private void jButton_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaActionPerformed
        String masp = txt_ma_sp.getText();
        if (masp.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khoa cần xóa", "Thông báo", 1);
        } else {
            int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (b == JOptionPane.YES_OPTION) {
                try {
                    try {
                        new sanphamDAO().deleteSP(masp);
                    } catch (SQLException ex) {

                    }
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Dữ liệu chưa thể xóa, có tồn tại lớp của khoa này.\nHãy xóa dữ liệu lớp của khoa này trước.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
                while (dtm.getRowCount() > 0) {
                    dtm.removeRow(0);
                }
                try {
                    loaddata();
                } catch (SQLException ex) {

                }
            }
            xoaText();
        }
    }//GEN-LAST:event_jButton_xoaActionPerformed

    private void jButton_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_luuActionPerformed
        String masp = txt_ma_sp.getText();
        String tensp = txt_ten_loai.getText();
        String gia = txt_gia_ban.getText();
        String maloai = listLoaiSP.get(cb_loaisp.getSelectedIndex()).getMaloai();
        sanpham sp = new sanpham(masp, tensp, Integer.parseInt(gia), maloai);
        try {
            long kt = new sanphamDAO().chekid(masp);
            if (kt != 0) {
                JOptionPane.showMessageDialog(this, "Mã bị trùng!", "Vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (isEdit == false) {
            try {
                sanpham insert = new sanphamDAO().addNew(sp);
                if (insert != null) {
                    showAll();
                    xoaText();
                }

            } catch (SQLException ex) {
                Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                sanpham update = new sanphamDAO().update(sp);
                if (update != null) {
                    showAll();
                    xoaText();
                }
            } catch (SQLException ex) {
                Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_luuActionPerformed

    private void jButton_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suaActionPerformed
        isEdit = true;
    }//GEN-LAST:event_jButton_suaActionPerformed

    private void jButton_preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_preActionPerformed
        trang--;
        try {
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            loaddataTrang(trang * 5 - 5);
        } catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel_trang.setText("" + trang);
    }//GEN-LAST:event_jButton_preActionPerformed

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
        trang++;
        try {
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            loaddataTrang(trang * 5 - 5);
        } catch (SQLException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel_trang.setText("" + trang);
    }//GEN-LAST:event_jButton_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new mainFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_loaisp;
    private javax.swing.JButton jButton_kluu;
    private javax.swing.JButton jButton_luu;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_pre;
    private javax.swing.JButton jButton_sua;
    private javax.swing.JButton jButton_them;
    private javax.swing.JButton jButton_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_trang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField txt_gia_ban;
    private javax.swing.JTextField txt_ma_sp;
    private javax.swing.JTextField txt_ten_loai;
    private javax.swing.JLabel txt_ten_sp;
    // End of variables declaration//GEN-END:variables

}
